### Uninstall "Python Environments" extension in order to run all cells using "Run All" button given above

In [1]:
import sys
print(sys.executable)

c:\Users\hp\miniconda3\envs\py39\python.exe


In [2]:
import numpy as np  

In [3]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [4]:
zeros = np.zeros([5, 4], dtype=int)
zerosFloat = np.zeros([5, 4], dtype=float)
print(zeros)
print(zerosFloat)   

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
identityMat = np.eye(3, dtype=int)
identityMat

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [6]:
arrangeInterval = np.arange(0, 11, 2)
arrangeInterval

array([ 0,  2,  4,  6,  8, 10])

In [7]:
evenList = np.linspace(-5, 5, 20)
evenList

array([-5.        , -4.47368421, -3.94736842, -3.42105263, -2.89473684,
       -2.36842105, -1.84210526, -1.31578947, -0.78947368, -0.26315789,
        0.26315789,  0.78947368,  1.31578947,  1.84210526,  2.36842105,
        2.89473684,  3.42105263,  3.94736842,  4.47368421,  5.        ])

In [8]:
randList = np.random.random([3])
randMat = np.random.random([3, 2])
print(randList)
print(randMat)

[0.99924771 0.38442831 0.93494238]
[[0.45329403 0.51952292]
 [0.28862293 0.91378888]
 [0.9604014  0.63904248]]


In [9]:
# random integers in range [0, 10)
randIntList = np.random.randint(0, 10, [3, 2])
randIntList

array([[3, 9],
       [8, 8],
       [7, 6]], dtype=int32)

In [10]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat

print(mat.ndim)
print(mat.shape)
print(mat.size)
print("Data type of the matrix =", mat.dtype)
print("Size of each item in bytes =", mat.itemsize)
print("Total size of the matrix in bytes =", mat.nbytes)
print(mat.data)
print(mat.T)

2
(3, 3)
9
Data type of the matrix = int64
Size of each item in bytes = 8
Total size of the matrix in bytes = 72
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
x = np.array([1, 24, 54])
# x
y = x[np.newaxis, :]
z = x[:, np.newaxis]
print("Dimension of z :", x.ndim)
print("Dimension of y :", y.ndim)
print("Dimension of z :", z.ndim)
print(y + z)
print((y + z).ndim)

Dimension of z : 1
Dimension of y : 2
Dimension of z : 2
[[  2  25  55]
 [ 25  48  78]
 [ 55  78 108]]
2


In [12]:
# Indexing and Slicing
mat = np.random.randint(0, 10, [3, 2])
print(mat, "\n-------")

print(mat[1, 1], "\n-------")
print(mat[1], "\n-------")
print(mat[1:], "\n-------")
print(mat[:, 1], "\n-------")
print(mat[:, 1:], "\n-------")

[[1 4]
 [6 8]
 [6 7]] 
-------
8 
-------
[6 8] 
-------
[[6 8]
 [6 7]] 
-------
[4 8 7] 
-------
[[4]
 [8]
 [7]] 
-------


## copy()

If changes are made to a subarray/submatrix, then those changes are reflected in the original matrix as well.
To avoid this and make a deep copy, use copy() function

In [13]:
mat = np.random.randint(0, 10, [3, 2])
print("Original mat:\n", mat)
shallowCopy = mat[:2,:]
deepCopy = mat[:2,:].copy()
print("Shallow copy:\n", shallowCopy)
print("Deep copy:\n", deepCopy)
shallowCopy[0, 0] = 100
deepCopy[1, 1] = 500
print("Shallow copy affected:\n", shallowCopy)
print("Deep copy affected:\n", deepCopy)
print("Original mat affected:\n", mat)


Original mat:
 [[5 3]
 [4 0]
 [7 5]]
Shallow copy:
 [[5 3]
 [4 0]]
Deep copy:
 [[5 3]
 [4 0]]
Shallow copy affected:
 [[100   3]
 [  4   0]]
Deep copy affected:
 [[  5   3]
 [  4 500]]
Original mat affected:
 [[100   3]
 [  4   0]
 [  7   5]]


In [14]:
distribution = [23, 54, 23, 7, 46.7, 76.4, 34.5, 19, 41, 8, 6, 2]

print("Mean =", np.mean(distribution))
print("25th Percentile =", np.percentile(distribution, 25))
print("Median =", np.median(distribution))
print("75th Percentile =", np.percentile(distribution, 75))
print("Standard Deviation =", np.std(distribution))
print("Variance =", np.var(distribution))
print("Maximum =", np.max(distribution))
print("Minimum =", np.min(distribution))
print("Sum =", np.sum(distribution))
print("Cumulative Sum =", np.cumsum(distribution))
print("Cumulative Product =", np.cumprod(distribution))
print("Product =", np.prod(distribution))

Mean = 28.383333333333336
25th Percentile = 7.75
Median = 23.0
75th Percentile = 42.425
Standard Deviation = 21.81310131294697
Variance = 475.81138888888887
Maximum = 76.4
Minimum = 2.0
Sum = 340.6
Cumulative Sum = [ 23.   77.  100.  107.  153.7 230.1 264.6 283.6 324.6 332.6 338.6 340.6]
Cumulative Product = [2.30000000e+01 1.24200000e+03 2.85660000e+04 1.99962000e+05
 9.33822540e+06 7.13440421e+08 2.46136945e+10 4.67660196e+11
 1.91740680e+13 1.53392544e+14 9.20355265e+14 1.84071053e+15]
Product = 1840710530184987.0


In [15]:
li = np.array([5, 6, 2, 0, 8, 3, 7])
type (li)
print(np.sort(li))
np.sort(li + 5)

[0 2 3 5 6 7 8]


array([ 5,  7,  8, 10, 11, 12, 13])