In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

## Series

In [3]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [4]:
s.values

array([ 1.,  3.,  5., nan,  6.,  8.])

In [5]:
s.index

RangeIndex(start=0, stop=6, step=1)

#### Panda Series vs. Numpy Array
Panda series have explicitly defined index (or label) associated with the values, which makes Panda series different from Numpy array


In [6]:
data = pd.Series([1, 4, 6.3, 10], index=['A', 'B', 'C', 'D'])
data

A     1.0
B     4.0
C     6.3
D    10.0
dtype: float64

The above data series may look similar to a regular python dictionay, but unlike dictionary, panda series can be sliced
 

In [7]:
data['A': 'C']

A    1.0
B    4.0
C    6.3
dtype: float64

## DataFrame
It is analogous to 2D array in numpy, but with both flexible row indices and flexible column names

In [8]:
df = pd.DataFrame(['A', 'B', 'C'], index=[10, 20, 30], columns=["letter"])
df

letter
10      A
20      B
30      C

In [9]:
stateDf = pd.DataFrame({'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]})
stateDf

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [10]:
area = pd.Series({'California': 423967, 'Texas': 695662, 'New York': 141297,
                  'Florida': 170312, 'Illinois': 149995})
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127, 'Florida': 19552860,
                        'Illinois': 12882135})

stateDf = pd.DataFrame({"area": area, "population": population})
stateDf

area  population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127
Florida     170312    19552860
Illinois    149995    12882135

In [11]:
print(stateDf.index)
print(stateDf.columns)

print(stateDf.columns.to_list(), type(stateDf.columns.to_list()))
print(stateDf.columns.to_numpy(), type(stateDf.columns.to_numpy()))

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Index(['area', 'population'], dtype='object')
['area', 'population'] <class 'list'>
['area' 'population'] <class 'numpy.ndarray'>


DataFrame can be created using Numpy structured array

In [12]:
a = np.zeros([5], dtype=[('A', 'int'), ('B', 'float')])
a

array([(0, 0.), (0, 0.), (0, 0.), (0, 0.), (0, 0.)],
      dtype=[('A', '<i8'), ('B', '<f8')])

In [13]:
pd.DataFrame(a)

A    B
0  0  0.0
1  0  0.0
2  0  0.0
3  0  0.0
4  0  0.0

DataFrame index is an immutable object in itself. It can be created separately, and shared between multiple Dataframes

In [14]:
ind = pd.Index(['A', 'B', 'C'])
ind

Index(['A', 'B', 'C'], dtype='object')

Index is immutable; cannot be modified

In [15]:
ind[2] = 'G'

TypeError: Index does not support mutable operations

In [16]:
print(pd.DataFrame(["Maths", "English", "Science"], index=ind))
print(pd.DataFrame(["Burger", "Apple", "Candy"], index=ind))


         0
A    Maths
B  English
C  Science
        0
A  Burger
B   Apple
C   Candy


In [17]:
data = pd.Series([1, 4, 6.3, 10], index=['A', 'B', 'C', 'D'])
data

A     1.0
B     4.0
C     6.3
D    10.0
dtype: float64

In [18]:
data['B']

np.float64(4.0)

In [19]:
'A' in data

True

In [20]:
print(data.keys())
print(list(data.keys()))

Index(['A', 'B', 'C', 'D'], dtype='object')
['A', 'B', 'C', 'D']


In [21]:
list(data.items())

[('A', 1.0), ('B', 4.0), ('C', 6.3), ('D', 10.0)]

In [22]:
# masking
data[data > 1.5]

B     4.0
C     6.3
D    10.0
dtype: float64

### loc, iloc and ix

In [23]:
data = pd.Series([1, 43.5, 6.3, 10, 11], index=['A', 'B', 'C', 'D', 'E'])
print(data)
print(data.loc['A'])
print(data.loc['A': 'D'])
print(data.iloc[0])
print(data.iloc[1])

A     1.0
B    43.5
C     6.3
D    10.0
E    11.0
dtype: float64
1.0
A     1.0
B    43.5
C     6.3
D    10.0
dtype: float64
1.0
43.5


In [24]:
area = pd.Series({'California': 423967, 'Texas': 695662, 'New York': 141297,
                  'Florida': 170312, 'Illinois': 149995})
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127, 'Florida': 19552860,
                        'Illinois': 12882135})

stateDf = pd.DataFrame({"area": area, "population": population})
stateDf

area  population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127
Florida     170312    19552860
Illinois    149995    12882135

In [25]:
stateDf.values

array([[  423967, 38332521],
       [  695662, 26448193],
       [  141297, 19651127],
       [  170312, 19552860],
       [  149995, 12882135]])

In [26]:
stateDf.T

California     Texas  New York   Florida  Illinois
area            423967    695662    141297    170312    149995
population    38332521  26448193  19651127  19552860  12882135

In [27]:
stateDf['density'] = stateDf['population'] / stateDf['area']
stateDf

area  population     density
California  423967    38332521   90.413926
Texas       695662    26448193   38.018740
New York    141297    19651127  139.076746
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763

In [28]:
stateDf.loc['Texas']

area          6.956620e+05
population    2.644819e+07
density       3.801874e+01
Name: Texas, dtype: float64

In [29]:
stateDf.iloc[1]

area          6.956620e+05
population    2.644819e+07
density       3.801874e+01
Name: Texas, dtype: float64

In [30]:
stateDf.loc['Texas': , 'area': 'population']

area  population
Texas     695662    26448193
New York  141297    19651127
Florida   170312    19552860
Illinois  149995    12882135

In [31]:
stateDf.loc['Texas': , ['population', 'density']]

population     density
Texas       26448193   38.018740
New York    19651127  139.076746
Florida     19552860  114.806121
Illinois    12882135   85.883763

In [32]:
stateDf['density']

California     90.413926
Texas          38.018740
New York      139.076746
Florida       114.806121
Illinois       85.883763
Name: density, dtype: float64

In [33]:
stateDf[stateDf['density'] > 100]

area  population     density
New York  141297    19651127  139.076746
Florida   170312    19552860  114.806121

In [34]:
stateDf.loc[:, ['area', 'density']]

area     density
California  423967   90.413926
Texas       695662   38.018740
New York    141297  139.076746
Florida     170312  114.806121
Illinois    149995   85.883763

In [35]:
points = pd.Series([4, 8, 15, 16, 23, 42])
points = points / 4
points

0     1.00
1     2.00
2     3.75
3     4.00
4     5.75
5    10.50
dtype: float64

Any item which is not present in one of the two series is assigned NaN after the operation

In [36]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127}, name='population')

population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

### Handling missing data

In [37]:
a = pd.Series(np.random.randint(0, 10, 4), index=list("ABCD"))
b = pd.Series(np.random.randint(0, 10, 4), index=list("ABCE"))
print("a =\n", a)
print("b =\n", b)
c = a+b
print("c =\n", c)

a =
 A    9
B    8
C    3
D    3
dtype: int32
b =
 A    6
B    2
C    4
E    4
dtype: int32
c =
 A    15.0
B    10.0
C     7.0
D     NaN
E     NaN
dtype: float64


### Fill the missing values with 0 

In [38]:
# fills the missing indices with 0 and then add the series
a.add(b, fill_value=0)

A    15.0
B    10.0
C     7.0
D     3.0
E     4.0
dtype: float64

In [39]:
mean = a.mean()
print("Mean of series a =", mean)
a.add(b, fill_value=mean)

Mean of series a = 5.75


A    15.00
B    10.00
C     7.00
D     8.75
E     9.75
dtype: float64

In case of DataFrame, we need to stack the dataframe 'A' in order to calculate its mean

In [40]:
A = pd.DataFrame(np.random.randint(0, 10, [2, 3]), index=list("XY"))
print("A =", "\n", A)
B = pd.DataFrame(np.random.randint(0, 10, [2, 3]), index=list("XZ"))
print("B =", "\n", B)


A = 
    0  1  2
X  2  9  1
Y  4  8  8
B = 
    0  1  2
X  8  2  5
Z  0  2  3


In [41]:
C = A + B
C

0     1    2
X  10.0  11.0  6.0
Y   NaN   NaN  NaN
Z   NaN   NaN  NaN

### Filling the missing values with Mean value

In [42]:
meanVal = A.stack().mean()
print("Mean of A =", meanVal)
A.add(B, fill_value=meanVal)


Mean of A = 5.333333333333333


0          1          2
X  10.000000  11.000000   6.000000
Y   9.333333  13.333333  13.333333
Z   5.333333   7.333333   8.333333

In [43]:
A = pd.DataFrame([[1, 2, 4], [8, 9, 0]], index=list("XY"))
print("A =", "\n", A)

A = 
    0  1  2
X  1  2  4
Y  8  9  0


In [44]:
print("A.index =", A.index.to_list())
print("A.columns =", A.columns.to_list())
print("A.loc['X'].index", A.loc['X'].index.to_list())

A.index = ['X', 'Y']
A.columns = [0, 1, 2]
A.loc['X'].index [0, 1, 2]


In [45]:
A.subtract(A.loc['X'], axis=0)

0   1   2
X NaN NaN NaN
Y NaN NaN NaN
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN

axis=0 means aligning index of Series A.loc['X'] with **index of DataFrame A** \
Index of A = [X, Y] \
Index of A.loc['X'] = [0, 1, 2] \
Because of no overlap the above result is calculated

In [46]:
A = pd.DataFrame([[1, 2, 4], [8, 9, 0]], index=list("XY"))
print("A =", "\n", A)

A = 
    0  1  2
X  1  2  4
Y  8  9  0


In [47]:
A.subtract(A.loc['X'], axis=1)

0  1  2
X  0  0  0
Y  7  7 -4

axis=1 means aligning index of Series A.loc['X'] with the **columns of DataFrame A** \
Index of A.loc['X'] = [0, 1, 2] \
Column of A = [0, 1, 2]

In [48]:
A = pd.DataFrame([[1, 2, 4], [8, 9, np.nan], [8, 9, 10]])
A

0  1     2
0  1  2   4.0
1  8  9   NaN
2  8  9  10.0

### Dropping Null Values

In [49]:
A.dropna()

0  1     2
0  1  2   4.0
2  8  9  10.0

In [50]:
# dropping NA values along different axis (column)
A.dropna(axis=1)

0  1
0  1  2
1  8  9
2  8  9

### Filling NA values with 0

In [51]:
A.fillna(0)

0  1     2
0  1  2   4.0
1  8  9   0.0
2  8  9  10.0

### Filling NA values with previous/next value

In [52]:
# fills previous value in place of NA (therefor forward filling)
A.ffill() # similar to A.fillna(method="ffill")

0  1     2
0  1  2   4.0
1  8  9   4.0
2  8  9  10.0

In [53]:
# fills next value in place of NA (therefor backward filling)
A.bfill() # similar to A.fillna(method="bfill")

0  1     2
0  1  2   4.0
1  8  9  10.0
2  8  9  10.0

#### If there is no previous or forward value, then the NA values remains.

### Combining Datasets

#### Concatenation

In [54]:
DF1 = pd.DataFrame([[1, 2, 4], [8, 9, 0]], index=list("XJ"), columns=list("ABC"))
DF2 = pd.DataFrame([[12, 23, 44], [85, 29, 10]], index=list("KJ"), columns=list("ABC"))
display("DF1", DF1); display("DF2", DF2)

'DF1'

A  B  C
X  1  2  4
J  8  9  0

'DF2'

A   B   C
K  12  23  44
J  85  29  10

In [55]:
pd.concat([DF1, DF2])

A   B   C
X   1   2   4
J   8   9   0
K  12  23  44
J  85  29  10

In [56]:
pd.concat([DF1, DF2], axis=1)

A    B    C     A     B     C
X  1.0  2.0  4.0   NaN   NaN   NaN
J  8.0  9.0  0.0  85.0  29.0  10.0
K  NaN  NaN  NaN  12.0  23.0  44.0

In [57]:
pd.concat([DF1, DF2], axis=1, join="inner")

A  B  C   A   B   C
J  8  9  0  85  29  10

#### Merge

In [58]:
A = pd.DataFrame([["JAKE", 2, 4], ["RACE", 9, 0]], index=list("XY"), columns=list("DBC"))
B = pd.DataFrame([["JAKE", 23, 44], ["RACE", 29, 10]], index=list("XY"), columns=list("XEF"))
display("A", A); display("B", B)

'A'

D  B  C
X  JAKE  2  4
Y  RACE  9  0

'B'

X   E   F
X  JAKE  23  44
Y  RACE  29  10

In [59]:
# Merging on columns
pd.merge(A, B, left_on="D", right_on="X")

D  B  C     X   E   F
0  JAKE  2  4  JAKE  23  44
1  RACE  9  0  RACE  29  10

In [60]:
# Merging on Index
pd.merge(A, B, left_index=True, right_index=True)

D  B  C     X   E   F
X  JAKE  2  4  JAKE  23  44
Y  RACE  9  0  RACE  29  10

In [61]:
# Join (same as merging on index)
A.join(B)

D  B  C     X   E   F
X  JAKE  2  4  JAKE  23  44
Y  RACE  9  0  RACE  29  10

### Task: Merge the following 3 datasets and rank US states and territories by their 2010 population density

In [ ]:
# !curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv
# !curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv
# !curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 57935  100 57935    0     0  43054      0  0:00:01  0:00:01 --:--:-- 43235
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   835  100   835    0     0    838      0 --:--:-- --:--:-- --:--:--   847
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:

In [133]:
pop = pd.read_csv("state-population.csv")
areas = pd.read_csv("state-areas.csv")
abbrevs = pd.read_csv("state-abbrevs.csv")

In [134]:
display(pop.head())
display(areas.head())
display(abbrevs.head())

state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

#### Finding missing values (NaN) in all datasets

In [135]:
pop.isnull().any()

state/region    False
ages            False
year            False
population       True
dtype: bool

In [136]:
pop.loc[pop["population"].isnull()]

state/region     ages  year  population
2448           PR  under18  1990         NaN
2449           PR    total  1990         NaN
2450           PR    total  1991         NaN
2451           PR  under18  1991         NaN
2452           PR    total  1993         NaN
2453           PR  under18  1993         NaN
2454           PR  under18  1992         NaN
2455           PR    total  1992         NaN
2456           PR  under18  1994         NaN
2457           PR    total  1994         NaN
2458           PR    total  1995         NaN
2459           PR  under18  1995         NaN
2460           PR  under18  1996         NaN
2461           PR    total  1996         NaN
2462           PR  under18  1998         NaN
2463           PR    total  1998         NaN
2464           PR    total  1997         NaN
2465           PR  under18  1997         NaN
2466           PR    total  1999         NaN
2467           PR  under18  1999         NaN

Now population has NaN values, which is simply due to available dataset.

In [137]:
pop.isnull().any()

state/region    False
ages            False
year            False
population       True
dtype: bool

In [138]:
areas.isna().any()

state            False
area (sq. mi)    False
dtype: bool

In [139]:
abbrevs.isna().any()

state           False
abbreviation    False
dtype: bool

#### Merging Population and Abbreviation dataset

In [140]:
popAbbrMerged = pd.merge(pop, abbrevs, how="outer", left_on="state/region", right_on="abbreviation")
popAbbrMerged.head()

state/region     ages  year  population   state abbreviation
0           AK    total  1990    553290.0  Alaska           AK
1           AK  under18  1990    177502.0  Alaska           AK
2           AK    total  1992    588736.0  Alaska           AK
3           AK  under18  1991    182180.0  Alaska           AK
4           AK  under18  1992    184878.0  Alaska           AK

Checking if merged dataset has mismatches (NaN)

In [141]:
popAbbrMerged.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
abbreviation     True
dtype: bool

In [142]:
popAbbrMerged.loc[popAbbrMerged["state"].isnull()]

state/region     ages  year   population state abbreviation
1872           PR  under18  1990          NaN   NaN          NaN
1873           PR    total  1990          NaN   NaN          NaN
1874           PR    total  1991          NaN   NaN          NaN
1875           PR  under18  1991          NaN   NaN          NaN
1876           PR    total  1993          NaN   NaN          NaN
...           ...      ...   ...          ...   ...          ...
2203          USA    total  2010  309326295.0   NaN          NaN
2204          USA  under18  2011   73902222.0   NaN          NaN
2205          USA    total  2011  311582564.0   NaN          NaN
2206          USA  under18  2012   73708179.0   NaN          NaN
2207          USA    total  2012  313873685.0   NaN          NaN

[96 rows x 6 columns]

In [143]:
popAbbrMerged.loc[popAbbrMerged["state"].isnull(), "state/region"].unique()

array(['PR', 'USA'], dtype=object)

The columns "state" and "abbreviation" of table "Abbreviation" did not have "Puerto Rico" and "United States", and "PR" and "USA" respectively, which is the cause of NaN values. \
This can be fixed by filling in appropriate entries

In [144]:
popAbbrMerged.loc[popAbbrMerged["state/region"] == "PR", "state"] = "Puerto Rico"
popAbbrMerged.loc[popAbbrMerged["state/region"] == "USA", "state"] = "United States"
popAbbrMerged.loc[popAbbrMerged["state/region"] == "PR", "abbreviation"] = "PR"
popAbbrMerged.loc[popAbbrMerged["state/region"] == "USA", "abbreviation"] = "USA"

In [152]:
# Checking for NaN values again (ignore the population NaN values as discussed earlier)
popAbbrMerged.isnull().any()

state/region    False
ages            False
year            False
population       True
state           False
abbreviation    False
dtype: bool

#### Merging the above merged dataset with Areas dataset

In [166]:
finalDf = pd.merge(popAbbrMerged, areas, how="outer", left_on="state", right_on="state")
display("(Rows, Columns) = " + str(finalDf.shape))
finalDf.head()

'(Rows, Columns) = (2544, 7)'

state/region     ages  year  population    state abbreviation  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama           AL        52423.0
1           AL    total  2012   4817528.0  Alabama           AL        52423.0
2           AL  under18  2010   1130966.0  Alabama           AL        52423.0
3           AL    total  2010   4785570.0  Alabama           AL        52423.0
4           AL  under18  2011   1125763.0  Alabama           AL        52423.0

Checking for NaN

In [167]:
finalDf.isnull().any()

state/region     False
ages             False
year             False
population        True
state            False
abbreviation     False
area (sq. mi)     True
dtype: bool

In [168]:
# Finding states that have no area values
finalDf.loc[finalDf["area (sq. mi)"].isnull(), "state"].unique()

array(['United States'], dtype=object)

**Since we need to rank states and regions of USA, we don't need rows that contain data of USA as whole. Therefore those rows are dropped**

In [172]:
display("Before dropping USA NaN values, (Rows, Columns) = " + str(finalDf.shape))
indicesOfUSARows = finalDf.loc[finalDf["state/region"] == "USA"].index
finalDf.drop(indicesOfUSARows, inplace=True)
display("After dropping USA NaN values, (Rows, Columns) = " + str(finalDf.shape))

'Before dropping USA NaN values, (Rows, Columns) = (2544, 7)'

'After dropping USA NaN values, (Rows, Columns) = (2496, 7)'

In [173]:
finalDf

state/region     ages  year  population    state abbreviation  \
0              AL  under18  2012   1117489.0  Alabama           AL   
1              AL    total  2012   4817528.0  Alabama           AL   
2              AL  under18  2010   1130966.0  Alabama           AL   
3              AL    total  2010   4785570.0  Alabama           AL   
4              AL  under18  2011   1125763.0  Alabama           AL   
...           ...      ...   ...         ...      ...          ...   
2539           WY  under18  1993    137458.0  Wyoming           WY   
2540           WY    total  1991    459260.0  Wyoming           WY   
2541           WY  under18  1991    136720.0  Wyoming           WY   
2542           WY  under18  1990    136078.0  Wyoming           WY   
2543           WY    total  1990    453690.0  Wyoming           WY   

      area (sq. mi)  
0           52423.0  
1           52423.0  
2           52423.0  
3           52423.0  
4           52423.0  
...             ...  
2539        97818.0  
2540        97818.0  
2541        97818.0  
2542        97818.0  
2543        97818.0  

[2496 rows x 7 columns]

In [174]:
finalDf["density"] = finalDf["population"] / finalDf["area (sq. mi)"]
finalDf.head()

state/region     ages  year  population    state abbreviation  \
0           AL  under18  2012   1117489.0  Alabama           AL   
1           AL    total  2012   4817528.0  Alabama           AL   
2           AL  under18  2010   1130966.0  Alabama           AL   
3           AL    total  2010   4785570.0  Alabama           AL   
4           AL  under18  2011   1125763.0  Alabama           AL   

   area (sq. mi)    density  
0        52423.0  21.316769  
1        52423.0  91.897221  
2        52423.0  21.573851  
3        52423.0  91.287603  
4        52423.0  21.474601

In [175]:
finalDf.isnull().any()

state/region     False
ages             False
year             False
population        True
state            False
abbreviation     False
area (sq. mi)    False
density           True
dtype: bool

Density has  NaN values, because some rows had NaN population values right from the very beginning, so drop those values as well.

In [197]:
finalDf.dropna(inplace=True)
display("(Rows, Columns) = " + str(finalDf.shape))
display(finalDf.head())
display(finalDf.isnull().any())


'(Rows, Columns) = (2476, 8)'

state/region     ages  year  population    state abbreviation  \
0           AL  under18  2012   1117489.0  Alabama           AL   
1           AL    total  2012   4817528.0  Alabama           AL   
2           AL  under18  2010   1130966.0  Alabama           AL   
3           AL    total  2010   4785570.0  Alabama           AL   
4           AL  under18  2011   1125763.0  Alabama           AL   

   area (sq. mi)    density  
0        52423.0  21.316769  
1        52423.0  91.897221  
2        52423.0  21.573851  
3        52423.0  91.287603  
4        52423.0  21.474601

state/region     False
ages             False
year             False
population       False
state            False
abbreviation     False
area (sq. mi)    False
density          False
dtype: bool

In [205]:
year2010Df = finalDf.loc[(finalDf["year"] == 2010) & (finalDf["ages"] == "total")].copy()
year2010Df.set_index("state/region", inplace=True)
year2010Df.sort_values(by="density", ascending=False, inplace=True)
display(year2010Df[["state", "density"]].head())
display(year2010Df[["state", "density"]].tail())

state      density
state/region                                   
DC            District of Columbia  8898.897059
PR                     Puerto Rico  1058.665149
NJ                      New Jersey  1009.253268
RI                    Rhode Island   681.339159
CT                     Connecticut   645.600649

state    density
state/region                         
SD            South Dakota  10.583512
ND            North Dakota   9.537565
MT                 Montana   6.736171
WY                 Wyoming   5.768079
AK                  Alaska   1.087509